//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADPClientDemo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                  {
                  ""clientID"":  ""88a73992-07f2-4714-ab4b-de782acd9c4d"",
                  ""clientSecret"": ""a130adb7-aa51-49ac-9d02-0d4036b63541"",
                  ""_sslCertPath"": ""..\\..\\Content\\certs\\apiclient_iat.pfx"",
                  ""_sslKeyPath"": ""..\\..\\Content\\certs\\apiclient_iat.key"",
                  ""sslCertPath"": ""..\\..\\Content\\certs\\cert.pem"",
                  ""sslKeyPath"": ""..\\..\\Content\\certs\\cert.key"",
                  ""sslKeyPass"": ""adpadp10"",
                  ""tokenServerURL"": ""https://iat-api.adp.com/auth/oauth/v2/token"",
                  ""disconnectURL"": ""https://iat-accounts.adp.com/auth/oauth/v2/logout"",
                  ""apiRequestURL"": ""https://iat-api.adp.com"",
                  ""responseType"": ""code"",
                  ""defaultexpiration"": 3600,
                  ""grantType"": ""client_credentials""
                  }
                ")]
        public string ClientCredentialConfiguration {
            get {
                return ((string)(this["ClientCredentialConfiguration"]));
            }
            set {
                this["ClientCredentialConfiguration"] = value;
            }
        }
    }
}
